# This is a test script for experimenting with the data cleaning process

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

def load_data(file_path):
    """
    Load the dataset from a CSV file.
    
    Args:
        file_path (str): Path to the CSV file.

    Returns:
        pd.DataFrame: Loaded dataset as a pandas DataFrame.
    """
    try:
        data = pd.read_csv(file_path)
        print("Data loaded successfully.")
        return data
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return None

def clean_data(input_file, output_file):
    """
    Cleans the stock market data by handling missing values and normalizing the data.

    Args:
        input_file (str): Path to the input CSV file.
        output_file (str): Path to the output CSV file.
    """
    try:
        # Load data
        data = load_data(input_file)
        if data is None:
            return

        # Convert relevant columns to numeric, coercing errors to NaN
        cols = ["price", "close", "high", "low", "open", "volume"]
        data[cols] = data[cols].apply(pd.to_numeric, errors="coerce")
        print("Converted relevant columns to numeric.")

        # Handle NaN values in the price column specifically
        if data["price"].isna().sum() > 0:
            print("Handling NaN values in the price column.")
            data["price"].fillna(data["price"].mean(), inplace=True)

        # Select numeric columns
        numeric_data = data.select_dtypes(include="number")
        print("Selected numeric columns.")
        
        # Fill missing values with the mean for other columns
        numeric_data.fillna(numeric_data.mean(), inplace=True)
        print("Missing values filled.")
        
        # Normalize data using Min-Max Scaling
        scaler = MinMaxScaler()
        data_scaled = pd.DataFrame(scaler.fit_transform(numeric_data), columns=numeric_data.columns)
        print("Data normalized.")
        
        # Save cleaned data
        data_scaled.to_csv(output_file, index=False)
        print(f"Cleaned data saved to {output_file}")
    except Exception as e:
        print(f"Error cleaning data: {str(e)}")  # Ensure error message is a string

def main():
    """
    Main function to test data cleaning.
    """
    # File path to test dataset
    input_file = "sandbox/test_stock_data.csv"  # Update this path if needed
    output_file = "sandbox/cleaned_stock_data.csv"  # Update this path if needed

    # Run the cleaning process
    clean_data(input_file, output_file)

if __name__ == "__main__":
    main()

# Generated by Nicole LeGuern
