import pandas as pd

def extract_features(input_file, output_file):
    """
    Extracts features from the stock market data.

    Args:
        input_file (str): Path to the input CSV file.
        output_file (str): Path to the output CSV file.
    """
    try:
        # Load data
        data = pd.read_csv(input_file)
        print("Data loaded successfully.")
        
        # Example feature extraction: calculate moving average
        data["moving_average"] = data["close"].rolling(window=5).mean()
        print("Features extracted.")
        
        # Save the featured data to the specific path
        data.to_csv(output_file, index=False)
        print(f"Featured data saved to {output_file}")

    except Exception as e:
        print(f"Error extracting features: {str(e)}")  # Ensure error message is a string

# Specify the input and output file paths
input_file = "C:/Projects/Simplified_Stock_Market_Predictor_AI/Sandbox/cleaned_test_stock_data.csv"
output_file = "C:/Projects/Simplified_Stock_Market_Predictor_AI/Sandbox/featured_test_stock_data.csv"

# Extract features
extract_features(input_file, output_file)

# Generated by Nicole LeGuern