import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.impute import SimpleImputer
import joblib

def develop_model(input_file, output_file):
    """
    Develops a machine learning model to predict stock prices and saves the trained model.

    Args:
        input_file (str): Path to the input CSV file.
        output_file (str): Path to save the trained model.
    """
    try:
        # Load data
        data = pd.read_csv(input_file)
        print("Data loaded successfully.")
        
        # Prepare features and target variable
        X = data[["close", "high", "low", "open", "volume", "moving_average"]]
        y = data["price"]
        
        # Handle missing values using SimpleImputer
        imputer = SimpleImputer(strategy="median")
        X = imputer.fit_transform(X)
        
        # Split data into training and testing sets
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        print("Data split into training and testing sets.")
        
        # Train the model
        model = LinearRegression()
        model.fit(X_train, y_train)
        print("Model trained.")
        
        # Save the trained model
        joblib.dump(model, output_file)
        print(f"Trained model saved to {output_file}")
        
        # Make predictions
        y_pred = model.predict(X_test)
        
        # Evaluate the model
        mse = mean_squared_error(y_test, y_pred)
        print(f"Model Mean Squared Error: {mse}")

    except Exception as e:
        print(f"Error developing model: {str(e)}")  # Ensure error message is a string

# Specify the input file path and output file path
input_file = "C:/Projects/Simplified_Stock_Market_Predictor_AI/Sandbox/featured_test_stock_data.csv"
output_file = "C:/Projects/Simplified_Stock_Market_Predictor_AI/Sandbox/trained_model.pkl"

# Develop the model
develop_model(input_file, output_file)

# Generated by Nicole LeGuern