import pandas as pd
import matplotlib.pyplot as plt
import joblib
from sklearn.impute import SimpleImputer

def visualize_predictions(input_file, model_file):
    """
    Visualizes the actual vs. predicted stock prices.

    Args:
        input_file (str): Path to the input CSV file.
        model_file (str): Path to the trained machine learning model file.
    """
    try:
        # Load data
        data = pd.read_csv(input_file)
        print("Data loaded successfully.")
        
        # Load the trained model
        model = joblib.load(model_file)
        print("Model loaded successfully.")
        
        # Prepare features and target variable
        X = data[["close", "high", "low", "open", "volume", "moving_average"]]
        y = data["price"]
        
        # Handle missing values using SimpleImputer
        imputer = SimpleImputer(strategy="median")
        X = imputer.fit_transform(X)
        
        # Make predictions
        y_pred = model.predict(X)
        
        # Plot actual vs. predicted prices
        plt.figure(figsize=(10, 6))
        plt.plot(y.values, label="Actual Prices")
        plt.plot(y_pred, label="Predicted Prices")
        plt.xlabel("Time")
        plt.ylabel("Stock Price")
        plt.title("Actual vs. Predicted Stock Prices")
        plt.legend()
        plt.show()

    except Exception as e:
        print(f"Error visualizing predictions: {str(e)}")  # Ensure error message is a string

# Specify the input file path and model file path
input_file = "C:/Projects/Simplified_Stock_Market_Predictor_AI/Sandbox/featured_test_stock_data.csv"
model_file = "C:/Projects/Simplified_Stock_Market_Predictor_AI/Sandbox/trained_model.pkl"

# Visualize the predictions
visualize_predictions(input_file, model_file)

# Generated by Nicole LeGuern